name: Custom Patches
on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:
  schedule:
    - cron: 0 0/4 * * *

jobs:
  Dolphin:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true



      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > sign.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          
      - name: Download and Patch Dolphin to SDK 29
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash src/build/custom.sh dolphin


      - name: Release
        uses: ncipollo/release-action@v1.21.0
        with:
         artifacts: |
          ./build/*.apk
         name: Dolphin-SDK29
         tag: Dolphin-SDK29
         bodyFile: build.log
         allowUpdates: true
  Eden:
   permissions: write-all
   runs-on: ubuntu-latest
   steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true



      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > sign.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY

      - name: Download and Patch Eden to PUBG
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash src/build/custom.sh eden

      - name: Release
        uses: ncipollo/release-action@v1.21.0
        with:
         artifacts: |
          ./build/*.apk
         name: Eden-PUBG
         tag: Eden-PUBG
         bodyFile: build.log
         allowUpdates: true
  FCL:
   permissions: write-all
   runs-on: ubuntu-latest
   steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true



      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > sign.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY

      - name: Download and Patch FCL to CoD
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash src/build/custom.sh fcl

      - name: Release
        uses: ncipollo/release-action@v1.21.0
        with:
         artifacts: |
          ./build/*.apk
         name: FCL-CoD
         tag: FCL-CoD
         bodyFile: build_log.txt
         allowUpdates: true

  Geode:
   permissions: write-all
   runs-on: ubuntu-latest
   steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true



      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > sign.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY

      - name: Download and Patch Geode to PUBGKR
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash src/build/custom.sh geode
      - name: Release
        uses: ncipollo/release-action@v1.21.0
        with:
         artifacts: |
          ./build/*.apk
         name: Geode-PUBGKR
         tag: Geode-PUBGKR
         bodyFile: build_log.txt
         allowUpdates: true
         
